// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMK3g9fVC8JIizehkLTQAKyRxqBGC3gbk',
    appId: '1:81674910652:web:4e834384801ee3f6ad49b9',
    messagingSenderId: '81674910652',
    projectId: 'whereismybus-c9c8e',
    authDomain: 'whereismybus-c9c8e.firebaseapp.com',
    storageBucket: 'whereismybus-c9c8e.appspot.com',
    measurementId: 'G-YXDS6YPN0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh272t1UpsWKXl6YoE-yJjm7qyBb6zOUg',
    appId: '1:81674910652:android:1de0be6d85ee2946ad49b9',
    messagingSenderId: '81674910652',
    projectId: 'whereismybus-c9c8e',
    storageBucket: 'whereismybus-c9c8e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoGyvHjxcbIpu-2TkSHLAVk2sT9xvcnp8',
    appId: '1:81674910652:ios:b793d510e98fb305ad49b9',
    messagingSenderId: '81674910652',
    projectId: 'whereismybus-c9c8e',
    storageBucket: 'whereismybus-c9c8e.appspot.com',
    iosBundleId: 'com.example.bus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoGyvHjxcbIpu-2TkSHLAVk2sT9xvcnp8',
    appId: '1:81674910652:ios:ee1bf7adf257c31dad49b9',
    messagingSenderId: '81674910652',
    projectId: 'whereismybus-c9c8e',
    storageBucket: 'whereismybus-c9c8e.appspot.com',
    iosBundleId: 'com.example.bus.RunnerTests',
  );
}
